fix(letschat): add missing volumes
Tested both deployments. Without these deployment fails:

error: Validation failed App "node" needs the following volumes: /usr/src/app/config, /usr/src/app/uploads; Please add those volumes